### PR TITLE
Fix bug of "undefined" as a winner

### PR DESCRIPTION
**Pull request by andrepgsilva**
Hey guys!

I have fixed the message "undefined" as the battle result and I refactored the "declare winner" method.

Best Regards

### CODE REVIEW

**Review by subhamgcon — CHANGES_REQUESTED** [review]
Hey @andrepgsilva, Thanks for your contributions but can you make sure that the undefined option is not replaced by a blank space(which is happening now) instead you can display the winner status.

**Comment by andrepgsilva** [comment]
Hello @subhamgcon!

I have finished the changes you requested.

Best Regards

**Review by subhamgcon — APPROVED** [review]
Well done!! 👍 ✔️

**Comment by subhamgcon** [comment]
@andrepgsilva Thanks for your awesome contribution! You can contribute more if you like! 

All the best!!

**Comment by andrepgsilva** [comment]
Thank you so much for your feedback!

I wish you all the best.

**Pull request merged**
